"""
UI Constants for ghdesk
Centralized configuration for layout dimensions and settings
"""

# Application metadata
APP_NAME = "ghdesk"
APP_TITLE = "ghdesk - GitHub Desktop Manager"
ORGANIZATION_NAME = "byteshiftlabs"

# Main window geometry
WINDOW_X = 100
WINDOW_Y = 100
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 800

# Splitter panel sizes (pixels)
SPLITTER_FILE_TREE_WIDTH = 220
SPLITTER_TABS_WIDTH = 500
SPLITTER_DETAILS_WIDTH = 480

# Repository table column widths
COLUMN_WIDTH_NAME = 180
COLUMN_WIDTH_OWNER = 120
COLUMN_WIDTH_PATH = 120
COLUMN_WIDTH_DESCRIPTION = 150
COLUMN_WIDTH_BRANCH = 150
COLUMN_WIDTH_STATUS = 100
COLUMN_WIDTH_VISIBILITY = 100
COLUMN_WIDTH_LICENSE = 120
COLUMN_WIDTH_UPDATED = 100
COLUMN_WIDTH_REMOTE = 200

# Dialog dimensions
DIALOG_LICENSE_WIDTH = 800
DIALOG_LICENSE_HEIGHT = 550
DIALOG_MESSAGE_BOX_MIN_WIDTH = 400
DIALOG_SPLITTER_LEFT = 250
DIALOG_SPLITTER_RIGHT = 550

# Pull Request dialog dimensions
PR_CREATE_DIALOG_WIDTH = 600
PR_CREATE_DIALOG_HEIGHT = 700
PR_CREATE_BODY_MIN_HEIGHT = 100

# Commit/Push dialog dimensions
COMMIT_PUSH_DIALOG_WIDTH = 1000
COMMIT_PUSH_DIALOG_HEIGHT = 700
COMMIT_PUSH_SPLITTER_LEFT = 300
COMMIT_PUSH_SPLITTER_RIGHT = 700

# Widget dimensions
WIDGET_THEME_COMBO_MIN_WIDTH = 120
WIDGET_LICENSE_LIST_MIN_WIDTH = 200
WIDGET_LIST_MAX_HEIGHT = 100
WIDGET_LIST_MAX_HEIGHT_MEDIUM = 150
WIDGET_SCROLL_MAX_HEIGHT = 400
WIDGET_COMMITS_MAX_HEIGHT = 300
WIDGET_COMMITS_ROW_HEIGHT = 30
WIDGET_COMMITS_HEADER_HEIGHT = 35
WIDGET_BUTTON_MIN_WIDTH_SMALL = 70
WIDGET_BUTTON_MIN_WIDTH_MEDIUM = 80
WIDGET_BUTTON_MIN_WIDTH_LARGE = 100

# Layout spacing
LAYOUT_MARGIN_STANDARD = 16
LAYOUT_MARGIN_COMPACT = 12
LAYOUT_SPACING_STANDARD = 12
LAYOUT_SPACING_COMPACT = 8
LAYOUT_NO_MARGINS = (0, 0, 0, 0)  # For setContentsMargins(*LAYOUT_NO_MARGINS)

# Timing (milliseconds)
STATUS_MESSAGE_TIMEOUT = 3000

# API limits
GITHUB_REPO_LIST_LIMIT = 200
