"""
UI Constants for ghdesk
Centralized configuration for layout dimensions and settings
"""

# Application metadata
APP_NAME = "ghdesk"
APP_TITLE = "ghdesk - GitHub Desktop Manager"
ORGANIZATION_NAME = "byteshiftlabs"

# Main window geometry
WINDOW_X = 100
WINDOW_Y = 100
WINDOW_WIDTH = 1400
WINDOW_HEIGHT = 800

# Splitter panel sizes (pixels)
SPLITTER_FILE_TREE_WIDTH = 220
SPLITTER_TABS_WIDTH = 500
SPLITTER_DETAILS_WIDTH = 480

# Repository table column widths
COLUMN_WIDTH_NAME = 180
COLUMN_WIDTH_OWNER = 120
COLUMN_WIDTH_PATH = 120
COLUMN_WIDTH_DESCRIPTION = 150
COLUMN_WIDTH_BRANCH = 150
COLUMN_WIDTH_STATUS = 100
COLUMN_WIDTH_VISIBILITY = 100
COLUMN_WIDTH_LICENSE = 120
COLUMN_WIDTH_UPDATED = 100
COLUMN_WIDTH_REMOTE = 200

# Dialog dimensions
PR_CREATE_DIALOG_WIDTH = 700
PR_CREATE_DIALOG_HEIGHT = 600
PR_CREATE_BODY_MIN_HEIGHT = 150

COMMIT_PUSH_DIALOG_WIDTH = 1000
COMMIT_PUSH_DIALOG_HEIGHT = 700
COMMIT_PUSH_SPLITTER_LEFT = 300
COMMIT_PUSH_SPLITTER_RIGHT = 700

# PR list widget
PR_LIST_FILTER_SPACING = 16
PR_LIST_AUTHOR_FILTER_WIDTH = 200
PR_LIST_REFRESH_BUTTON_WIDTH = 100

# PR detail view
PR_DETAIL_CONTENT_MARGIN = 16
PR_DETAIL_CONTENT_SPACING = 16
PR_DETAIL_LABEL_SPACING = 4
